### ISSUE TITLE
Current dependencies (0.4.4) are incompatible with Python 3.8

### ISSUE THREAD

**Issue by manics** [ome/ome-ansible-molecule#23]
pyflakes is installed as a dependency of one of the modules pinned in this repository
That version can't be used with Python 3.8: https://github.com/PyCQA/pyflakes/issues/367
and as a testing our roles with Python 3.8 on the host system fails.

**Comment by sbesson** [comment]
Assuming this is now resolved by `ome-ansible-molecule` 0.5.0. Will re-open if the problem persists
